### PR TITLE
testing the new conda resolver

### PR DESCRIPTION
**Pull request by bgruening**
This PR is just to test the new resolver and can be closed if successful.

### CODE REVIEW

**Comment by bgruening** [comment]
@lecorguille, @gregvonkuster can you please try this with your flavor as well and report and problem to https://github.com/galaxyproject/galaxy/pull/3391

**Comment by gregvonkuster** [comment]
@bgruening I've updated this repository https://hub.docker.com/r/gregvonkuster/docker-galaxy-csg/ and tested it with your latest conda enhancements and everything works perfectly!  ;)  Thanks for the awesome work!

I am waiting on a merge for these remaining conda enhancements https://github.com/galaxyproject/tools-devteam/pulls so that I can finish upgrading this repository https://hub.docker.com/r/gregvonkuster/docker-galaxy-chip-exo/ for some additional testing.

**Comment by bgruening** [comment]
Cool, good to know. Can you try to get the devtools stuff also under testing?

**Comment by gregvonkuster** [comment]
@bgruening I've updated https://github.com/gregvonkuster/docker-galaxy-ChIP-exo to use your latest conda implementation and my docker image seems to be working fine with regard to conda dependency installation.

However, I noticed a potential issue.  My docker recipe installs 4 data manager tools, but when I attempt to execute one (e.g., BWA-MEM index builder), the "Source FASTA Sequence" drop-down include no options.  Is this a know issue?

**Comment by bgruening** [comment]
@gregvonkuster has this worked before? I think you need to run at first the data manager to get the source reference faster files, and to run this data manager you need to run the datamanager that gives you the list of reference sequences.

**Comment by bgruening** [comment]
Seems to work, is now in dev.

**Comment by gregvonkuster** [comment]
@bgruening Ah, yes, I'm sure I missed that - sorry.  The tools all worked well.  Thanks!  ;)

**Pull request closed without merging**
