### PR TITLE
Update image 

### PR DESCRIPTION
**Pull request by bebatut**
Hi,
- I update image version and remove some commands
- I add new versions of the tools

Bérénice

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks!

**Comment by bgruening** [comment]
Pull requests that have a failing status can’t be merged from a phone.     Sorry

**Comment by bebatut** [comment]
I think it failed because `deepTool`  installation takes to much time

**Comment by bgruening** [comment]
We should target 16.07 and activate conda installation this will be much faster.

**Comment by bebatut** [comment]
I will do that. Did we need to conserve all these revisions for the tools or could we just keep the last ones?

**Comment by bgruening** [comment]
Keeping all that have conda support would be nice. I think there is some value in keeping old versions in our images ... If they don't grow to much in size.
On Aug 30, 2016 4:40 PM, Bérénice Batut notifications@github.com wrote:I will do that. Did we need to conserve all these revisions or could we just keep the last ones?

**Comment by bebatut** [comment]
Well, Travis is still failing because `deepTools` installation takes to much time :(

**Comment by bgruening** [comment]
I guess we need to activate tool_dependency installation. But this looks good as it is. Thanks. Dockrhub and quay.io will build it.

**Comment by bebatut** [comment]
How can I activate the `tool_dependency` installation?

**Pull request merged**
